### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by remonsec** [cujanovic/Open-Redirect-Payloads#2]
Hello i am new in web app testing 
so here i have to replace  WHITELISTEDDOMAIN with my targetsite.com
and then i have to put this command in my terminal ! 

targetsite.com="www.test.com" && sed 's/www.whitelisteddomain.tld/'"$targetsite.com"'/' Open-Redirect-payloads.txt > Open-Redirect-payloads-burp-"$targetsite.com".tmp && sed 's/@www.whitelisteddomain.tld/@'"$targetsite.com"'/' Open-Redirect-payloads-burp-"$targetsite.com".tmp > Open-Redirect-payloads-burp-"$targetsite.com".txt && echo "$targetsite.com" | awk -F. '{if ($1 =="www") print "//not"$2"."$NF"/"; else print "//not"$1"."$NF"/";}' >> Open-Redirect-payloads-burp-"$targetsite.com".txt && echo "$targetsite.com" | awk -F. '{if ($1 =="www") print "http://not"$2"."$NF"/"; else print "http://not"$1"."$NF"/";}' >> Open-Redirect-payloads-burp-"$targetsite.com".txt && echo "$targetsite.com" | awk -F. '{print "http://"$0"."$NF"/"}' >> Open-Redirect-payloads-burp-"$targetsite.com".txt && rm -f Open-Redirect-payloads-burp-"$targetsite.com".tmp && echo -e "\nDone. Filename: $(pwd)/Open-Redirect-payloads-burp-"$targetsite.com".txt"

**Comment by cujanovic** [comment]
Hello, the idea is that www.test.com is whitelisted on www.test.com so only input the name of the site your are testing. Example:

> WHITELISTEDDOMAIN="www.google.com" && sed 's/www.whitelisteddomain.tld/'"$WHITELISTEDDOMAIN"'/' Open-Redirect-payloads.txt > Open-Redirect-payloads-burp-"$WHITELISTEDDOMAIN".tmp && sed 's/@www.whitelisteddomain.tld/@'"$WHITELISTEDDOMAIN"'/' Open-Redirect-payloads-burp-"$WHITELISTEDDOMAIN".tmp > Open-Redirect-payloads-burp-"$WHITELISTEDDOMAIN".txt && echo "$WHITELISTEDDOMAIN" | awk -F. '{if ($1 =="www") print "//not"$2"."$NF"/"; else print "//not"$1"."$NF"/";}' >> Open-Redirect-payloads-burp-"$WHITELISTEDDOMAIN".txt && echo "$WHITELISTEDDOMAIN" | awk -F. '{if ($1 =="www") print "http://not"$2"."$NF"/"; else print "http://not"$1"."$NF"/";}' >> Open-Redirect-payloads-burp-"$WHITELISTEDDOMAIN".txt && echo "$WHITELISTEDDOMAIN" | awk -F. '{print "http://"$0"."$NF"/"}' >> Open-Redirect-payloads-burp-"$WHITELISTEDDOMAIN".txt && rm -f Open-Redirect-payloads-burp-"$WHITELISTEDDOMAIN".tmp && echo -e "\nDone. Filename: $(pwd)/Open-Redirect-payloads-burp-"$WHITELISTEDDOMAIN".txt"
